# Generated by Django 4.2 on 2023-05-02 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='photos/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('camera', models.CharField(blank=True, max_length=200, null=True)),
                ('lens', models.CharField(blank=True, max_length=200, null=True)),
                ('keywords', models.CharField(blank=True, max_length=250, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('year_taken', models.CharField(blank=True, max_length=10, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
